apiVersion: v1
kind: Service
metadata:
  name: cwv-runtime-beta
  namespace: cwv-beta
  labels:
    app: cwv-runtime-beta
    tier: cwv-runtime-beta
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
  selector:
    app: cwv-runtime-beta
    tier: cwv-runtime-beta
