apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cwv-runtime-beta
  namespace: cwv-beta
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: cwv-runtime-beta
        tier: cwv-runtime-beta
    spec:
      nodeName: k8s-t-10
      containers:
      - name: cwv-runtime-beta
        image: hub.cwv.io/cwv/cwv-runtime-beta:v1.0.2
        volumeMounts:
          - mountPath: /opt/bruntime/logs/
            name: shared-volume
        env:
          #- name: GET_HOSTS_FROM
          # value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
          - name: JAVA_OPTS
            value: "-Dfile.encoding=UTF8"
        ports:
        - containerPort: 80
      volumes:
      - name: shared-volume
        hostPath:
          # directory location on host
          path: /mnt/resource/logs
          # this field is optional
          type: Directory